FROM ubuntu:20.04 AS UBUNTU_20
MAINTAINER JK

ENV DEBIAN_FRONTEND noninteractive
ENV PIP_NO_INPUT 1

# Install tools required for project
RUN apt-get update && apt-get install -y \
  git \
  neovim \
  tmux \
  curl \
  build-essential \
  libxml2-dev \
  libxslt-dev \
  libxslt-dev \
  libhdf5-dev \
  libpq-dev \
  libssl-dev \
  libffi-dev \
  xvfb \
  xterm \
  wget \
  man-db \
  gcc-multilib \
  g++-multilib \
  python3-dev \
  python3-pip \
  libffi-dev \
  virtualenvwrapper \
  gdb-multiarch \
  libreadline-gplv2-dev \
  libncurses5 libncurses5-dev libncursesw5 \
  libncursesw5-dev libsqlite3-dev tk-dev \
  libgdbm-dev libbz2-dev cmake && \
 apt-get -y autoremove && apt-get -y clean && \
 apt-get -y autoclean && \
 rm -rf /var/cache/apt/archives/lists/*

# Add 32 bit architecture support for IDA
RUN dpkg --add-architecture i386 && apt-get -y update


RUN pip3 install \
  ipdb \
  ipython 


# install gef
RUN wget -q -O- https://github.com/hugsy/gef/raw/master/scripts/gef.sh | sh

WORKDIR /
